export const MutationKeys = {
  LOGIN: 'LOGIN',
  LOGOUT: 'LOGOUT',
  UPLOAD_MEDIA: 'UPLOAD_MEDIA',
  UPDATE_ME: 'UPDATE_ME',
  CHANGE_PASSWORD: 'CHANGE_PASSWORD',
  ADD_ACCOUNT: 'ADD_ACCOUNT',
  UPDATE_ACCOUNT: 'UPDATE_ACCOUNT',
  DELETE_ACCOUNT: 'DELETE_ACCOUNT',
  ADD_DISH: 'ADD_DISH',
  UPDATE_DISH: 'UPDATE_DISH',
  DELETE_DISH: 'DELETE_DISH'
}
