export const QueryKeys = {
  ACCOUNT_PROFILE: 'ACCOUNT_PROFILE',
  ACCOUNT_LIST: 'ACCOUNT_LIST',
  ACCOUNT_DETAIL: 'ACCOUNT_DETAIL',
  DISH_LIST: 'DISH_LIST',
  DISH_DETAIL: 'DISH_DETAIL',
  TABLE_DETAIL: 'TABLE_DETAIL',
  TABLE_LIST: 'TABLE_LIST',
  GUEST_ORDER_LIST: 'GUEST_ORDER_LIST',
  ORDER_LIST: 'ORDER_LIST',
  ORDER_DETAIL: 'ORDER_DETAIL',
  GUEST_LIST: 'GUEST_LIST',
  DASHBOARD_INDICATORS: 'DASHBOARD_INDICATORS'
}
