export const QueryKeys = {
  ACCOUNT_PROFILE: 'ACCOUNT_PROFILE',
  ACCOUNT_LIST: 'ACCOUNT_LIST',
  ACCOUNT_DETAIL: 'ACCOUNT_DETAIL',
  DISH_LIST: 'DISH_LIST',
  DISH_DETAIL: 'DISH_DETAIL',
  TABLE_DETAIL: 'TABLE_DETAIL',
  TABLE_LIST: 'TABLE_LIST'
}
